{
  description = "Fast Spotify client with native GUI written in Rust";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };

  outputs = { self, nixpkgs, flake-utils }:
    let
      cargoLockOutputHashes = {
        "cubeb-0.27.0" = "sha256-qq+AM9GbD0DAVcr2VrbtxDpSkb/FOMY75IQylXVG5Uw=";
        "druid-0.8.3" = "sha256-O9CBDRHcyDxa0MAqTtOipn0EPnm7o//bdQX/3hZpSJM=";
        "druid-enums-0.1.0" = "sha256-KJvAgKxicx/g+4QRZq3iHt6MGVQbfOpyN+EhS6CyDZk=";
      };

      mkPsstPackage = pkgs: pkgs.rustPlatform.buildRustPackage {
        pname = "psst";
        version = "0.1.0";
        src = ./.;

        cargoLock = {
          lockFile = ./Cargo.lock;
          outputHashes = cargoLockOutputHashes;
        };

        nativeBuildInputs = with pkgs; [
          pkg-config
          rustPlatform.bindgenHook
        ];

        buildInputs = with pkgs; [
          openssl
        ] ++ pkgs.lib.optionals pkgs.stdenv.hostPlatform.isLinux [
          alsa-lib
          gtk3
          cairo
          glib
          pango
          atk
          gdk-pixbuf
          dbus
        ] ++ pkgs.lib.optionals pkgs.stdenv.hostPlatform.isDarwin [
          apple-sdk
          libiconv
        ];

        postInstall = ''
          ln -s $out/bin/psst-gui $out/bin/psst

          ${pkgs.lib.optionalString pkgs.stdenv.hostPlatform.isDarwin ''
            mkdir -p $out/Applications/Psst.app/Contents/MacOS
            mkdir -p $out/Applications/Psst.app/Contents/Resources

            ln -s $out/bin/psst-gui $out/Applications/Psst.app/Contents/MacOS/psst-gui
            cp psst-gui/assets/logo.icns $out/Applications/Psst.app/Contents/Resources/logo.icns 2>/dev/null || true

            cat > $out/Applications/Psst.app/Contents/Info.plist <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>
    <string>psst-gui</string>
    <key>CFBundleIconFile</key>
    <string>logo.icns</string>
    <key>CFBundleIdentifier</key>
    <string>com.jpochyla.psst</string>
    <key>CFBundleName</key>
    <string>Psst</string>
    <key>CFBundleDisplayName</key>
    <string>Psst</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleShortVersionString</key>
    <string>0.1.0</string>
    <key>CFBundleVersion</key>
    <string>0.1.0</string>
    <key>LSMinimumSystemVersion</key>
    <string>11.0</string>
    <key>NSHighResolutionCapable</key>
    <true/>
</dict>
</plist>
EOF
          ''}
        '';

        meta = with pkgs.lib; {
          description = "Fast and native Spotify client";
          homepage = "https://github.com/jpochyla/psst";
          license = licenses.mit;
          mainProgram = "psst-gui";
        };
      };

      mkModule = isHomeManager: { config, lib, pkgs, ... }:
        let
          cfg = config.programs.psst;
          toCssRule = name: val:
            let
              propName = if lib.hasPrefix "--" name then name else "--${lib.replaceStrings ["_"] ["-"] name}";
            in "    ${propName}: ${toString val};";

          themeCss =
            let
              declarations = lib.concatStringsSep "\n" (lib.mapAttrsToList toCssRule cfg.theme);
            in ''
              /* Generated by Nix */
              ${lib.optionalString (cfg.theme != {}) ''
              :root {
              ${declarations}
              }
              ''}
              ${cfg.extraCss}
            '';
        in {
          options.programs.psst = {
            enable = lib.mkEnableOption "Psst Spotify client";
            package = lib.mkOption {
              type = lib.types.package;
              default = self.packages.${pkgs.stdenv.hostPlatform.system}.default or (mkPsstPackage pkgs);
              description = "The Psst package to install.";
            };
            theme = lib.mkOption {
              type = lib.types.attrsOf (lib.types.oneOf [ lib.types.str lib.types.int lib.types.float lib.types.bool ]);
              default = {};
              example = {
                grey-000 = "#fdf6e3";
                window-background-color = "#232a2e";
                font-family = "system-ui";
                font-size-normal = "13px";
              };
              description = "Theme options converted to CSS variables for ~/.config/psst/theme.css.";
            };
            extraCss = lib.mkOption {
              type = lib.types.lines;
              default = "";
              description = "Extra raw CSS to append to theme.css.";
            };
          };

          config = lib.mkIf cfg.enable (
            if isHomeManager then {
              home.packages = [ cfg.package ];
              xdg.configFile."psst/theme.css" = lib.mkIf (cfg.theme != {} || cfg.extraCss != "") {
                text = themeCss;
              };
            } else {
              environment.systemPackages = [ cfg.package ];
              environment.etc."xdg/psst/theme.css" = lib.mkIf (cfg.theme != {} || cfg.extraCss != "") {
                text = themeCss;
              };
            }
          );
        };
    in
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = import nixpkgs { inherit system; };
        psst = mkPsstPackage pkgs;
      in
      {
        packages = {
          default = psst;
          psst = psst;
          psst-gui = psst;
        };

        devShells.default = import ./shell.nix { inherit pkgs; };
      }
    ) // {
      overlays.default = final: prev: {
        psst = mkPsstPackage final;
      };

      nixosModules = {
        default = mkModule false;
        psst = mkModule false;
      };

      homeManagerModules = {
        default = mkModule true;
        psst = mkModule true;
      };
    };
}
